name: Track File Changes with Full Commit History

on:
  push:  # Runs on all branches
    paths:
      - '**.ts'
      - '**.js'
      - '**.php'

jobs:
  track-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find changed files
        id: changed_files
        run: echo "FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.(ts|js|php)$' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Process file updates
        run: |
          for file in $FILES; do
            if [[ -f "$file" ]]; then
              commit_history=$(git log --format="%H %an %ad" -- "$file")
              history_block="/*\n * Update History:\n"

              while read -r line; do
                commit_hash=$(echo $line | awk '{print $1}')
                author=$(echo $line | awk '{print $2}')
                date=$(echo $line | awk '{print $3, $4, $5}')
                commit_url="https://github.com/${{ github.repository }}/commit/$commit_hash"
                history_block+=" * $date - $author - $commit_url\n"
              done <<< "$commit_history"

              history_block+=" */\n"

              if ! grep -q "Update History" "$file"; then
                echo -e "$history_block$(cat $file)" > "$file"
              else
                sed -i "/Update History/,/*\//d" "$file"
                echo -e "$history_block$(cat $file)" > "$file"
              fi
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated file: Added full commit history" || echo "No changes made."
          git push origin HEAD || echo "Already up to date."
